Generate usage documentation
taskchampion/taskchampion pull request #236
Opened 2021-05-12 18:51 UTC by djmitche

This introduces a `generate` binary that updates the documentation based on the built-in usage.  This will ensure that the docs match `ta help`.

2021-05-18 01:31 UTC, dbr commented
Asking mostly because I'm planning to do something similar at some point [for auto-generating screenshots in mdbook](https://github.com/imgui-rs/imgui-rs/pull/482), did you investigate at all the mdbook "preprocessor" feature to implement this?

https://rust-lang.github.io/mdBook/for_developers/preprocessors.html

Would be neater in that the source files remain "clean", and it also uses the mdbook parser. However this may be excessive in this case, and also maybe not quite as nice since `reports.md` etc wouldn't contain anything but the placeholder, so only the generated mdbook would be readable :thinking:

2021-05-18 01:38 UTC, djmitche commented
I didn't know about that functionality -- I'll take a look!

2021-05-18 16:49 UTC, djmitche commented
Yeah, this looks like a good choice, but will be a significant refactor.  Thanks!

2021-05-22 00:48 UTC, djmitche commented
Hopefully that's green this time.  Thanks for the tip!  This is much nicer.

2021-05-23 23:42 UTC, dbr requested changes

2021-05-23 23:42 UTC, dbr commented on README.md
> +The `generate` binary generates files that are checked into the repository.
This is section is outdated by `usage-docs` I think?

2021-05-23 23:42 UTC, dbr commented on build-docs.sh
> +    git worktree add docs/tmp gh-pages
Might be worth adding a few comments to what each of these are doing - all makes perfect sense, just a bit hard to determine what each line is doing on first glance (e.g "make working copy of gh-pages in doc/tmp/", "remove old generated docs" etc)

2021-05-23 23:43 UTC, dbr commented
One reasonable looking clippy lint left! :grimacing: Also few very minor notes, but otherwise looks really good - the mdbook processor thing seems quite neat!

2021-05-25 05:24 UTC, dbr approved these changes

2021-05-26 15:03 UTC, merged