Support "wait"
taskchampion/taskchampion pull request #250
Opened 2021-05-30 14:11 UTC by djmitche

This implements wait in reports, debug/info, and modification.

It includes most of, but not a full set of timestamp parsers.  I'll push the rest out to another issue.

Fixes #83.

2021-06-01 11:04 UTC, dbr requested changes

2021-06-01 11:04 UTC, dbr commented on cli/src/argparse/modification.rs
> +    pub wait: Option<Option<DateTime<Utc>>>,
..I think this might be the first `Option<Option<...` I've seen 🥳

2021-06-01 11:04 UTC, dbr commented on cli/src/argparse/modification.rs
> +                is un-set.  See the documentation for the timestamp syntax.",
Maybe worth including a very short example like `wait:1day` as well as `wait:` to give some indication of the syntax?

2021-06-01 12:54 UTC, djmitche commented on docs/src/time.md
> + * A date of the format `YYYY-MM-DD` is interpreted as _local_ midnight on the given date.
How about "midnight at the beginning of the given date"?

2021-06-01 12:54 UTC, djmitche commented on taskchampion/src/task.rs
> +        let ts = Utc.ymd(3000, 1, 1).and_hms(0, 0, 0);
Yep.  Good luck, future world!

2021-06-01 12:56 UTC, djmitche commented on cli/src/argparse/args/colon.rs
> +/// Recognizes a colon-prefixed pair
Your point about the terminology still stands, though -- "colon prefixed" suggests ":foo".

2021-06-01 12:56 UTC, djmitche commented on cli/src/argparse/mod.rs
> +    pub(crate) static ref NOW: DateTime<Utc> = Utc::now();
No, the value is always used, even in non-test code.

2021-06-01 13:16 UTC, djmitche commented on docs/src/time.md
> +Durations can be given in a dizzying array of units.
Case 1 happend to me a while back.  But, I'd rather not _change_ the meaning of something that is probably in TW users' fingers.

2021-06-01 13:17 UTC, djmitche commented on docs/src/time.md
> +Durations can be given in a dizzying array of units.
If we did want to disambiguate `m`, I think the better choice would be to eliminate it and require either `min` or `mo`.. thoughts?

2021-06-01 13:24 UTC, dbr commented on docs/src/time.md
> +Durations can be given in a dizzying array of units.
Yep agreed - `min`/`minute`, `mo`/`month` seems like a good solution to the aMbiguity!

2021-06-01 13:24 UTC, djmitche commented on docs/src/time.md
> +Durations can be given in a dizzying array of units.
^^ I did that.  "Explicit is better than implicit" :)

2021-06-02 02:07 UTC, dbr approved these changes
LGTM!

2021-06-03 21:51 UTC, merged